"""add reason+score to unanswered

Revision ID: c9636baac678
Revises: c2286ba5f52b
Create Date: 2025-07-18 11:04:44.305499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9636baac678'
down_revision: Union[str, Sequence[str], None] = 'c2286ba5f52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unanswered_queries', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('unanswered_queries', sa.Column('score', sa.Float(), nullable=True))
    # op.alter_column('unanswered_queries', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unanswered_queries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('unanswered_queries', 'score')
    op.drop_column('unanswered_queries', 'reason')
    # ### end Alembic commands ###
